# Generated by Django 3.1 on 2020-08-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghostpost',
            name='boast_or_roast',
        ),
        migrations.AddField(
            model_name='ghostpost',
            name='is_boast',
            field=models.BooleanField(default=True),
        ),
    ]
