# Generated by Django 3.1 on 2020-08-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostapp', '0002_auto_20200820_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
